/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz4a;
 
 import org.junit.jupiter.api.Test;
 import static org.junit.jupiter.api.Assertions.*;
 
 
 class AppTest {
 
 
     //ตัวอย่าง 1 ให้สร้าง Employee Employee(1, "John Doe", 150000) และตรวจสอบว่าเงินเดือน เป็น 150000
     @Test void createEmployee() {
         Employee Employee = new Employee(1, "John Cana", 150000);
         System.out.println(Employee.getEmployeeId());
         System.out.println(Employee.getName());
         System.out.println(Employee.calculateSalary());
 
     }
 
     //ข้อ 2 ตรวจสอบว่า Salary ตั้งให้ติดลบไม่ได้
     @Test void SalaryCannotBeNegative() {
         Employee Employee = new Employee(1, "John Cena", -50000);
         if (Employee.calculateSalary() <= 0) {
             System.err.println("Salay cant be negative");
         } else {
             System.out.println("Nice, your salary is not negative");
         }
     }
 
     //ข้อ 3 ตรวจสอบว่า Bonus เป็น 20% ของ เงินเดือน(Salary)
     //ต้องมีการแก้ไข code ใน Manager.java ให้ถูกต้อง
     @Test void Bonus20() {
         Manager Manager = new Manager(1, "John Doe", 150000, null, 20);
         Manager.displayDetails();
     }
 }